### ISSUE TITLE
Employees Not Showing Up on the "Employees" Tab When you Click on Site Name

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#10]
I created employee 'Alyvia Pruit' for site McNellies Tulsa. But when you Click on McNellies Tulsa, and look at the Site employee list, Alyvia Pruit does not show up. Several other employees are missing from this site as well. 
![employee](https://cloud.githubusercontent.com/assets/24447345/21076673/3a0c1240-bef7-11e6-8eef-e3789ff2b0a2.PNG)
![employee2](https://cloud.githubusercontent.com/assets/24447345/21076678/55006e52-bef7-11e6-8677-eaaaa7fe7b0f.PNG)

**Comment by nmunos40** [comment]
Use Yokozuna OKC as an example site. If you click on the site, zero employees are showing up. But on the employee dashboard home page it looks like two employees currently work there.

**Comment by bmunos** [comment]
Can you try to re-replicate. I cant seem to find an employee that fits this issue. If you replicate can you tell me the steps. Specifically how you were adding an employee. Was it from the employee dashboard screen, or was it from the site dashboard screen?

**Comment by nmunos40** [comment]
This was happening repeatedly yesterday, but I am having trouble recreating the defect today. But the steps are below. 

Replication Steps:
1 From home page, click on Employee Dashboard.
2 Select top left icon with the "+" symbol to add employee.
3 From drop down select site - in this example, El Guapo's
4 Enter First name - this example, "destiny"
5 Enter Last name - this example "Malone"
6  Select Position - "manager"
7 Enter email address - "destiny@yahoo.com
8 manually enter date of 08-10-2012
9 leave term date blank
10 Check "salaried" and "still employed" under employee status
11 Select create employee

**Comment by bmunos** [comment]
Take another look at this. I think the employee is being flagged as a manager. If so we can close this.
