### ISSUE TITLE
"obtained" Button for Employee Liscenses and Employee Learning Not Working

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#13]
If you create an Employee License and select "obtained" nothing appears on the Liscence summary. 

![liscence](https://cloud.githubusercontent.com/assets/24447345/21082702/9e5ef442-bfa6-11e6-8e74-1745181fa8d0.PNG)

![liscence 2](https://cloud.githubusercontent.com/assets/24447345/21082708/c2279474-bfa6-11e6-8daa-1d3a1e214e75.PNG)

This is example was for employee Destiny Malone.

**Comment by bmunos** [comment]
This issue is caused by the name Obtained?. I need to remove the Question mark and update the form fields. This requires a new migration.

**Comment by bmunos** [comment]
This issue has been resolved. I have also updated all views to show Yes/No for true false
