### ISSUE TITLE
Time Stamp on Expiration Date Entry Screen/Manual Entry

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#14]
Didn't know if the "00:00:00" should be in this field. 

![time](https://cloud.githubusercontent.com/assets/24447345/21082752/83fb833a-bfa7-11e6-9f2d-7103524d8f17.PNG)

Also, just tried to manually enter the date in this field and got taken to this screen"

![date](https://cloud.githubusercontent.com/assets/24447345/21082767/bd3f6508-bfa7-11e6-9c92-5d36b2be4aff.PNG)

**Comment by bmunos** [comment]
This should be resolved
