### ISSUE TITLE
Hitting "Cancel" when Creating a New Lisense and Training Requirement Error Out

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#16]
When in the create license or training requirement creating screen, hitting cancel takes you to the error screen.

![error](https://cloud.githubusercontent.com/assets/24447345/21083198/cd9689dc-bfb0-11e6-9a62-e593c48c0850.PNG)
![capture](https://cloud.githubusercontent.com/assets/24447345/21083201/f4c61a40-bfb0-11e6-9aa7-006181e593e7.PNG)

**Comment by bmunos** [comment]
Fixed and ready for re-test
