### ISSUE TITLE
Should you be allowed to enter the same lisence or training requirements twice for the same employee?

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#17]
If you look at Kitty Fox, she has two of the same licenses and training requirements. I accidently entered these twice for the same employee. Should the user be notified you are trying to add the same license twice for the same employee? I think if the user is allowed to do this it will interfere with their ability to track timelines. They may not know which one is correct or needs attention. 

![addingseverallisence](https://cloud.githubusercontent.com/assets/24447345/21083260/346ea206-bfb2-11e6-87f6-4aca2979c1c2.PNG)

**Comment by bmunos** [comment]
After discussing this we decided to leave this. Not a bug. We will make the assumption the user knows what they are doing.
