### ISSUE TITLE
Error Message Received when hit Cancel on the Editing Empoyee Training Requirements Screen.

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#20]
I was running through this screen and when you edit a training requirement, but hit the cancel button on this screen:

![training dog gub](https://cloud.githubusercontent.com/assets/24447345/21297975/fc928ecc-c54e-11e6-9f88-cb6091a00f9d.PNG)

you get this error message:

![training req 2](https://cloud.githubusercontent.com/assets/24447345/21297985/199eb69e-c54f-11e6-9a79-b88b371a308f.PNG)

**Comment by nmunos40** [comment]
This error is also received when you hit the cancel button on this screen:

![edit license](https://cloud.githubusercontent.com/assets/24447345/21298070/cb1dd926-c550-11e6-94ae-40861abeafd2.PNG)

**Comment by bmunos** [comment]
Both should be fixed
