### ISSUE TITLE
The word "Edit" needs to be capitalized

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#21]
on both the employee licenses page and the employee learning page. 

![caps](https://cloud.githubusercontent.com/assets/24447345/21337616/8983f362-c634-11e6-81c4-6222e30230c2.PNG)
![caps2](https://cloud.githubusercontent.com/assets/24447345/21337624/9afccd8a-c634-11e6-94e2-890ce7cf281e.PNG)

**Comment by nmunos40** [comment]
- The "Create New Permit" button needs to have the word "New" capitalized. I cant take a screenshot.
- I think the word "all" needs to be capitalized in "View All Licenses" and "View All Training Items"

**Comment by bmunos** [comment]
Good Catch. Fixed Both.
