### ISSUE TITLE
Date Entry Format Desciption 

### ISSUE THREAD

**Issue by nmunos40** [bmunos/mcnellies-permits#9]
When creating an employee, if you input a date without dashes (ex. 08092016) in the 'Hired Date" column it will not give you an error message and the new employee will be created. But the hire date will be blank on the employee's profile. Should they receive an error code if they input the date the incorrect way? Maybe include an example of the correct date format in the header?
![date1](https://cloud.githubusercontent.com/assets/24447345/21076554/1726f112-bef4-11e6-93f1-645f8844f4c1.PNG)
![date2](https://cloud.githubusercontent.com/assets/24447345/21076557/24ffcd86-bef4-11e6-9923-86b2ad5578dd.PNG)

**Comment by bmunos** [comment]
I have logged this under a bigger enhancement request, which is to add real-time form validation for all from fields.
